services:
  # Main application
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=localhost
      - DEBUG=true
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/youtube_service
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./downloads:/app/downloads
      - .env:/app/.env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  # PostgreSQL database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=youtube_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  # Redis for caching and Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Celery worker
  celery-worker:
    build: .
    command: celery -A app.tasks.download_tasks worker --loglevel=info --concurrency=2
    environment:
      - ENVIRONMENT=localhost
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/youtube_service
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./downloads:/app/downloads
      - .env:/app/.env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  # Optional: Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    profiles:
      - tools

  # Optional: pgAdmin for PostgreSQL management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - db
    profiles:
      - tools

volumes:
  postgres_data:
  redis_data: