"""Initial migration - create download_jobs table

Revision ID: dfbe7de3e5a3
Revises: 
Create Date: 2025-09-04 12:05:07.959963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dfbe7de3e5a3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "download_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("channel_name", sa.String(), nullable=True),
        sa.Column("upload_date", sa.DateTime(), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=True),
        sa.Column("like_count", sa.Integer(), nullable=True),
        sa.Column("quality", sa.String(), nullable=True),
        sa.Column("include_transcription", sa.Boolean(), nullable=True),
        sa.Column("audio_only", sa.Boolean(), nullable=True),
        sa.Column("output_format", sa.String(), nullable=True),
        sa.Column("subtitle_languages", sa.String(), nullable=True),
        sa.Column("video_path", sa.String(), nullable=True),
        sa.Column("transcription_path", sa.String(), nullable=True),
        sa.Column("thumbnail_path", sa.String(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("video_codec", sa.String(), nullable=True),
        sa.Column("audio_codec", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("max_retries", sa.Integer(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_download_jobs_id"), "download_jobs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_download_jobs_status"),
        "download_jobs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_jobs_url"), "download_jobs", ["url"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_download_jobs_url"), table_name="download_jobs")
    op.drop_index(op.f("ix_download_jobs_status"), table_name="download_jobs")
    op.drop_index(op.f("ix_download_jobs_id"), table_name="download_jobs")
    op.drop_table("download_jobs")
    # ### end Alembic commands ###
